---
title: "Add_Loops"
author: "MaoHuang"
date: "3/10/2020"
output: html_document
runtime: shiny 
---

## Founder population parameters
```{r, echo=TRUE,results="hide",message=FALSE, warning=FALSE}
library(AlphaSimR)
```

```{r founder parameters}
Ne=60       # Historical effective population size, estimated via E(r2)=1/(1+4*Ne*c)
nInd<-800   # Number of founders
nChr<-31    # Number of chr
segSites<-500   # Number of segregating sites per chromosome
SP_ploidy<-2L   # Ploidy
bp<-1e+08       # Base pair length of chromosome
genLen=1        # Genetic length of chromosome in Morgans

nSnpPerChr<-100  # Number of SNP per chromosome
nQtlPerChr<-100  # Number of QTL per chromosome
mean_Trait<-0    # Trait mean
var_Trait<-1     # Trait variance
varE<-2          # *** This is starting H=0.33,  H=0.1 or H=0.5

```

**Number of individuals to  phenotype *400* vs *1000* **
```{r}
nCrosses<-400  ## ?? Use shiny to render the number of crosses
n_gp<-nCrosses/2
```

**Number of reps and cycles **
```{r}
nrep<-20  ## ?? Use shiny to render
cycle <-5
```

## Define the selection *Random* vs *Top*
```{r Simulation}
selection<-"rand" ## ?? Use shiney to render?
```

```{r}
Mean_g_Rep<-matrix(nrow=length(cycle),ncol=nrep)
Sd_g_Rep<-matrix(nrow=length(cycle),ncol=nrep)

for (i in 1:nrep){
  
  for (y in 1:years){ 
 founderPop<-runMacs2(nInd=nInd,nChr=nChr,segSites=segSites,Ne=Ne,bp=bp,genLen=1,inbred=TRUE,ploidy=SP_ploidy, returnCommand = FALSE, nThreads = NULL)
    
    SP = SimParam$new(founderPop)
    SP$addTraitA(nQtlPerChr=nQtlPerChr, mean=mean_Trait,var=var_Trait,corA=NULL)
    SP$addSnpChip(nSnpPerChr=nSnpPerChr)
    SP$setGender("yes_sys")
    SP$setTrackRec(TRUE)
    
    pop <- newPop(founderPop, simParam=SP)
    pop<-setPheno(pop,varE=varE,simParam=SP)
    genMean=meanG(pop)
    
    generation<- vector(length=cycle+1,mode="list")
    generation[[1]]<-pop   ### cycle 0, founder pop
    
 # popList<-NULL   
 # 
 #    
 #    if(j=1){
 #        GP0_DH<-makeDH(generation[[1]],nDH=1,simParam=SP)
 #        
 #        females<-selectInd(pop=GP0_DH,gender="F",nInd=n_gp,trait=1,use=selection,simParam=SP)
 #        males<-selectInd(pop=GP0_DH,gender="M",nInd=n_gp,trait=1,use=selection,simParam=SP)
 #        
 #        GP_F<-row.names(pullQtlGeno(females))
 #        GP_M<-row.names(pullQtlGeno(males))
 #        
 #        GP_F_2<-GP_F[sample(length(GP_F))]
 #        GP_M_2<-GP_M[sample(length(GP_M))]
 #        
 #        # Each GP used to make crosses twice
 #        GP_Fs<-c(GP_F,GP_F_2) 
 #        GP_Ms<-c(GP_M,GP_M_2)
 #        
 #        crossPlan<-cbind(GP_Fs,GP_Ms)
 #        
 #        Pops[[j]]<-GP0_DH
 #        ## Cross to create SP1
 #        SP[[j]]<-makeCross(Pops[[j]],crossPlan=crossPlan,simParam=SP) ## !!!!Update GP0_DH
 #        SP[[j]]<-setPheno(SP[[j]],varE=2,simParam=SP)
 #        
 #        ## Random Select amongst SP1
 #        SPj_s[[j]]<-selectInd(SP[[j]],nInd=100,trait=1,use=selection,simParam=SP)
 #        
 #        ## Make GP DH using SP1
 #        GPj_DH[[j]]<-makeDH(SPj_s[[j]],nDH=25,simParam=SP)	### !!!
 #        
 #        #popList<-list(popList,SP[[i]])
 #                
 #        ####
 #        ### !!! OR Select Top
 #        # SP1_s<-selectInd(SP1,nInd=100,trait=1,selectTop=TRUE,use="pheno",simParam=SP)
 #        ####
 #        
 #        
 #        
 #        
 #        #### cycle 2
 #        ## Randomly select 200 as female, then randomly select another 200 as male
 #        females[[j]]<-selectInd(pop=Pops[[j]],gender="F",nInd=n_gp,trait=1,use="rand",simParam=SP)
 #      
 #        males[[j]]<-selectInd(pop=Pops[[j]],gender="M",nInd=n_gp,trait=1,use="rand",simParam=SP)
 #        
 #        
 #        #### 
 #        GP_F<-row.names(pullQtlGeno(females))
 #        GP_M<-row.names(pullQtlGeno(males))
 #        
 #        GP_F_2<-GP_F[sample(length(GP_F))]
 #        GP_M_2<-GP_M[sample(length(GP_M))]
 #        
 #        GP_Fs<-c(GP_F,GP_F_2)
 #        GP_Ms<-c(GP_M,GP_M_2)
 #        
 #        crossPlan<-cbind(GP_Fs,GP_Ms)
 #        
 #        ## Cross to create SP2
 #        SP2<-makeCross(GP0_DH,crossPlan=crossPlan,simParam=SP)	
 #        SP2<-setPheno(SP2,varE=2,simParam=SP)
 #        
 #        ## Select amongst SP2 
 #        SP2_s<-selectInd(SP2,nInd=100,trait=1,use="rand",simParam=SP)					
 #        
 #        ### !!! OR			 
 #        # SP2_s<-selectInd(SP2,nInd=100,trait=1,selectTop=TRUE,use="pheno",simParam=SP)	
 #        ####	
 #        
 #        ## Make GP DH using SP2
 #        GP2_DH<-makeDH(SP2_s,nDH=25,simParam=SP)	### !!!
 
    GP0_DH<-makeDH(generation[[1]],nDH=1,simParam=SP)	### !!! When n_gp=200, use 1
	GP0_DH_all<-pullQtlGeno(GP0_DH)	
	dim(GP0_DH_all)
####
n_gp<-200 ## !!!
####


# ####### 500 Indi, 2GP/SP
# GP0_DH<-makeDH(generation[[1]],nDH=2,simParam=SP)	### !!! When n_gp=5 needs to use 2			GP0_DH_all<-pullQtlGeno(GP0_DH)
#	dim(GP0_DH_all)
# ####
# n_gp<-500  ##!!!
# ####


## Randomly select 200 as female, then randomly select another 200 as male
females<-selectInd(pop=GP0_DH,gender="F",nInd=n_gp,trait=1,use="rand",simParam=SP)
males<-selectInd(pop=GP0_DH,gender="M",nInd=n_gp,trait=1,use="rand",simParam=SP)	

GP_F<-row.names(pullQtlGeno(females))
GP_M<-row.names(pullQtlGeno(males))

GP_F_2<-GP_F[sample(length(GP_F))]	  					 
GP_M_2<-GP_M[sample(length(GP_M))] 					 

GP_Fs<-c(GP_F,GP_F_2)
GP_Ms<-c(GP_M,GP_M_2)

crossPlan<-cbind(GP_Fs,GP_Ms)

## Cross to create 400 SP1
SP1<-makeCross(GP0_DH,crossPlan=crossPlan,simParam=SP)	
SP1<-setPheno(SP1,varE=2,simParam=SP)

## Random Select amongst SP1
SP1_s<-selectInd(SP1,nInd=100,trait=1,use="rand",simParam=SP)					

####	
### !!! OR Select Top		 
# SP1_s<-selectInd(SP1,nInd=100,trait=1,selectTop=TRUE,use="pheno",simParam=SP)	
####	

## Make GP DH using SP1
GP1_DH<-makeDH(SP1_s,nDH=25,simParam=SP)	### !!!


#### Year 2, exactly the same scheme as in Year 1
## Randomly select 200 as female, then randomly select another 200 as male
females<-selectInd(pop=GP0_DH,gender="F",nInd=n_gp,trait=1,use="rand",simParam=SP)

males<-selectInd(pop=GP0_DH,gender="M",nInd=n_gp,trait=1,use="rand",simParam=SP)	
GP_F<-row.names(pullQtlGeno(females))
GP_M<-row.names(pullQtlGeno(males))

GP_F_2<-GP_F[sample(length(GP_F))]	  					 
GP_M_2<-GP_M[sample(length(GP_M))] 					 

GP_Fs<-c(GP_F,GP_F_2)
GP_Ms<-c(GP_M,GP_M_2)

crossPlan<-cbind(GP_Fs,GP_Ms)

## Cross to create 400 SP2
SP2<-makeCross(GP0_DH,crossPlan=crossPlan,simParam=SP)	
SP2<-setPheno(SP2,varE=2,simParam=SP)

## Select amongst SP2 
SP2_s<-selectInd(SP2,nInd=100,trait=1,use="rand",simParam=SP)					
	
### !!! OR			 
# SP2_s<-selectInd(SP2,nInd=100,trait=1,selectTop=TRUE,use="pheno",simParam=SP)	
####	

## Make GP DH using SP2
GP2_DH<-makeDH(SP2_s,nDH=25,simParam=SP)	### !!!


    

 popList<-list(SP1,SP2)
 TP<-NULL
 GS<-NULL
 GEBV<-NULL
 
 SP_s<-NULL
 GP_DH<-NULL
 
 GP_DH[[1]]<-GP0_DH
 GP_DH[[2]]<-GP1_DH
 
 ### loop for Year 3 to 5
 for (y in 3:5){
    
     
     #### cycle 4
     ## Build GS model using SP1+SP2+SP3
     ## popList=list(SP1,SP2,SP3)

     
            TP[[y]]<-mergePops(popList)     ### only has info from 3-5
            GS[[y]]<-RRBLUP(TP[[y-2]],traits=1,simParam=SP)  ### only has info from 3-5
            
            ## GEBVs on GP(y-1)s
            GEBV[[y]]<-setEBV(GP_DH[[y-1]],GS[[y]],simParam=SP)  ### y-1???
            
            ## Select GP1s GEBVs, generate SP3s
            females<-selectInd(pop=GEBV[[y]],gender="F",nInd=n_gp,selectTop=TRUE,trait=1,use="ebv",simParam=SP)
            
            males<-selectInd(pop=GEBV[[y]],gender="M",nInd=n_gp,selectTop=TRUE,trait=1,use="ebv",simParam=SP)
            
            GP_F<-row.names(pullQtlGeno(females))
            GP_M<-row.names(pullQtlGeno(males))
            
            GP_F_2<-GP_F[sample(length(GP_F))]
            GP_M_2<-GP_M[sample(length(GP_M))]
            
            GP_Fs<-c(GP_F,GP_F_2)
            GP_Ms<-c(GP_M,GP_M_2)
            
            crossPlan<-cbind(GP_Fs,GP_Ms)
            
            ## Cross to create SPy
            SP[[y]]<-makeCross(GP1_DH_GEBV,crossPlan=crossPlan,simParam=SP)
            SP[[y]]<-setPheno(SP[[y]],varE=2,simParam=SP)
            
            ## Select amongst SPy 
            SP_s[[y]]<-selectInd(SP[[y]],nInd=100,trait=1,use="rand",simParam=SP)
            
            ### !!! OR			 
            # SP3_s<-selectInd(SP3,nInd=100,trait=1,selectTop=TRUE,use="pheno",simParam=SP)	
            ####	
            
            ## Make GP_DH_y using SPy
            GP_DH[[y]]<-makeDH(SP_s[[y]],nDH=25,simParam=SP)
            
            
             popList=list(popList,SP[[y]])  ###
            
        }
        
        
 }
        






```
